include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    unnecessary_import: warning
    unused_shown_name: warning
    duplicate_import: warning

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    sized_box_for_whitespace: false
    
formatter:
  trailing_commas: preserve
  page_width: 120
